version: '3'
services:  
    postgres:
        image: postgres
        volumes:
        - C:\Users\Mediasoft\docker\volumes\postgres:/var/lib/postgresql/data
        environment:
        - "POSTGRES_PASSWORD=docker"      
        ports:
        - "5432:5432"