DROP TABLE IF EXISTS Attribute_values;
DROP TABLE IF EXISTS Attributes;
DROP TABLE IF EXISTS Product_images;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Manufacturers;
DROP TABLE IF EXISTS Categories;